package com.admom.mygreendaotest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.bme.hitsz.kevin.coolweather.db.City;
import cn.bme.hitsz.kevin.coolweather.db.Province;
import cn.bme.hitsz.kevin.coolweather.db.Town;

import com.admom.mygreendaotest.CityDao;
import com.admom.mygreendaotest.ProvinceDao;
import com.admom.mygreendaotest.TownDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig provinceDaoConfig;
    private final DaoConfig townDaoConfig;

    private final CityDao cityDao;
    private final ProvinceDao provinceDao;
    private final TownDao townDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        provinceDaoConfig = daoConfigMap.get(ProvinceDao.class).clone();
        provinceDaoConfig.initIdentityScope(type);

        townDaoConfig = daoConfigMap.get(TownDao.class).clone();
        townDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        provinceDao = new ProvinceDao(provinceDaoConfig, this);
        townDao = new TownDao(townDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Province.class, provinceDao);
        registerDao(Town.class, townDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        provinceDaoConfig.clearIdentityScope();
        townDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public ProvinceDao getProvinceDao() {
        return provinceDao;
    }

    public TownDao getTownDao() {
        return townDao;
    }

}
